### ISSUE TITLE
Set up secret API keys and authorization between communicating microservices

### ISSUE THREAD

**Issue by yuriy-pavlov** [dycons/compose#1]
Set up secrets/API keys between the following microservices, with authorization only for necessary demo1 workflows:
* Dataset Delivery -> Consents (authorize GET only)
* Relay -> Consents (authorize GET and PUT only)
* REMS -> Data Directory (authorize POST consent initialization only)
* Data Directory -> Consents (authorize POST consent initialization only)

**Comment by sh-ura** [comment]
WON'T DO
Closing due to repo archival.
