### ISSUE TITLE
Participant Frontend: hook up to Key Relay /consents endpoint (serving fixed data)

### ISSUE THREAD

**Issue by micfok** [dycons/compose#29]
## PR Summary

This pull request completes #29 through the following:
- Compose: Updates the readme indicating that pp-react now requires relay to be running
- Compose: Updates `.default.env` and `docker-compose.yaml` to include a relay host environment variable
- Relay: Server CORS settings configured to permit all hosts
- Participant Portal React: Fetches consents from the relay service (using hard coded JWT)

## Dependencies
- Relay: https://github.com/dycons/relay/pull/9
- Participant Portal: https://github.com/dycons/participant-portal/pull/11

**Comment by sh-ura** [comment]
WON'T DO
Closing due to repo archival.
